name: netease_common
description: A common Flutter package for NetEase.
version: 2.0.0
homepage: https://yunxin.163.com/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.0
  intl: any
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
