name: nim_chatkit_ui
description: Chat UI base on ChatKit.
version: 10.6.0-ohos
homepage: https://github.com/netease-kit/nim-uikit-flutter

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

# Remove this line if you wish to publish to pub.dev
#publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  netease_common_ui:
#    ">=10.5.0 <10.6.0"
    path: ../../common/netease_common_ui


  netease_corekit:
#    ">=1.3.0 <1.4.0"
    path: ../../netease_corekit/netease_corekit
  nim_chatkit:
#    ">=10.5.0 <10.6.0"
    path: ../nim_chatkit
  netease_plugin_core_kit:
#    ^10.0.0
      path: ../../plugin/netease_plugin_core_kit

  netease_common:
#    ^1.0.4
    path: ../../common/common

  nim_core_v2:
    git:
      url: "https://github.com/netease-kit/NIM-Flutter-SDK-OHOS.git"

#  呼叫组件
#  netease_callkit_ui:
#    ^3.7.1+2
#    path: ../../callkit/callkit_ui

  scroll_to_index: ^3.0.1
  image_picker:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/image_picker/image_picker"
  cached_network_image: ^3.3.1
  video_player:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/video_player/video_player"
  photo_view: ^0.14.0
  audioplayers:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers
  visibility_detector: ^0.4.0+2
#  image_gallery_saver_plus: ^4.0.1
  image_gallery_saver:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_image_gallery_saver.git
  fluttertoast:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_fluttertoast"
  dio: ^5.3.0
  intl: any
  flutter_svg: ^2.0.7
  provider: ^6.0.0
  yunxin_alog: ^2.0.0
  connectivity_plus:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/connectivity_plus/connectivity_plus"
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  collection: ^1.15.0
  file_picker: ^8.0.7
  file_picker_ohos: 1.0.1
  open_filex:
    path: ../../fluttertpc_open_filex
  extended_text_field: ^16.0.2
#  支持Markdown
  flutter_markdown:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/flutter_markdown"
  #  录音
  flutter_sound:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sound.git"
      ref: "br_v9.28.0_ohos"
  lottie: ^3.2.0
  uuid: ^4.4.0
  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"
  lpinyin: ^2.0.3

  #  呼叫组件
  netease_callkit_ui: ^3.7.1+2
  permission_handler: ^11.0.1

dependency_overrides:
  flutter_sound_web: null
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  permission_handler_ohos:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_permission_handler.git
      path: permission_handler_ohos
      ref: br_permission_handler_v11.3.1_ohos
  image_picker:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/image_picker/image_picker"
  uuid: ^4.4.0
  file: ^7.0.0
  flutter_cache_manager: ^3.3.2
  http: ^1.2.0
  sqflite:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: ./sqflite
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  netease_common_ui:
    #    ">=10.5.0 <10.6.0"
    path: ../../common/netease_common_ui
  netease_common:
    #    ^1.0.4
    path: ../../common/common
  fluttertoast:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_fluttertoast"
  nim_core_v2:
    git:
      url: "https://github.com/netease-kit/NIM-Flutter-SDK-OHOS.git"
  win32: 5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
   - images/
   - emoji/default/
   - lottie/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
